version: '3.8'

services:
  service-registry:
    build:
      args:
        - SPRING_PROFILES_ACTIVE=docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build:
      args:
        - SPRING_PROFILES_ACTIVE=docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  order-service:
    build:
      args:
        - SPRING_PROFILES_ACTIVE=docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./order-service:/app

  user-service:
    build:
      args:
        - SPRING_PROFILES_ACTIVE=docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./user-service:/app
