server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    org.springframework.web: DEBUG
    techieamit_it: DEBUG

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#        trace: false
#        web-admin-password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false  # restricts access to localhost only
        trace: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true